# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rmvnorm <- function(mean, Precision) {
    .Call('_SoftBart_rmvnorm', PACKAGE = 'SoftBart', mean, Precision)
}

choll <- function(Sigma) {
    .Call('_SoftBart_choll', PACKAGE = 'SoftBart', Sigma)
}

fit_logistic <- function(X, Y, num_iter) {
    .Call('_SoftBart_fit_logistic', PACKAGE = 'SoftBart', X, Y, num_iter)
}

fit_copula <- function(counts, sigma, num_iter, num_leap) {
    .Call('_SoftBart_fit_copula', PACKAGE = 'SoftBart', counts, sigma, num_iter, num_leap)
}

fit_logitnormal_2 <- function(counts, mu, Sigma_inv, theta_init, num_iter, num_leap) {
    .Call('_SoftBart_fit_logitnormal_2', PACKAGE = 'SoftBart', counts, mu, Sigma_inv, theta_init, num_iter, num_leap)
}

fit_logitnormal_nu <- function(counts, Omega_inv, theta_init, num_iter, num_leap) {
    .Call('_SoftBart_fit_logitnormal_nu', PACKAGE = 'SoftBart', counts, Omega_inv, theta_init, num_iter, num_leap)
}

fit_logitnormal <- function(counts, tau, i_vec, j_vec, num_iter, num_leap) {
    .Call('_SoftBart_fit_logitnormal', PACKAGE = 'SoftBart', counts, tau, i_vec, j_vec, num_iter, num_leap)
}

rcpparma_hello_world <- function() {
    .Call('_SoftBart_rcpparma_hello_world', PACKAGE = 'SoftBart')
}

rcpparma_outerproduct <- function(x) {
    .Call('_SoftBart_rcpparma_outerproduct', PACKAGE = 'SoftBart', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('_SoftBart_rcpparma_innerproduct', PACKAGE = 'SoftBart', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('_SoftBart_rcpparma_bothproducts', PACKAGE = 'SoftBart', x)
}

rlgam <- function(shape) {
    .Call('_SoftBart_rlgam', PACKAGE = 'SoftBart', shape)
}

SoftBart <- function(X, Y, X_test, group, alpha, beta, gamma, sigma, shape, width, num_tree, sigma_hat, k, alpha_scale, alpha_shape_1, alpha_shape_2, tau_rate, num_tree_prob, temperature, Graph, num_burn, num_thin, num_save, num_print, update_sigma_mu, update_s, update_alpha, update_beta, update_gamma, update_tau, update_tau_mean, update_num_tree, graph_laplacian) {
    .Call('_SoftBart_SoftBart', PACKAGE = 'SoftBart', X, Y, X_test, group, alpha, beta, gamma, sigma, shape, width, num_tree, sigma_hat, k, alpha_scale, alpha_shape_1, alpha_shape_2, tau_rate, num_tree_prob, temperature, Graph, num_burn, num_thin, num_save, num_print, update_sigma_mu, update_s, update_alpha, update_beta, update_gamma, update_tau, update_tau_mean, update_num_tree, graph_laplacian)
}

do_mh <- function(loglik_new, loglik_old, new_to_old, old_to_new) {
    .Call('_SoftBart_do_mh', PACKAGE = 'SoftBart', loglik_new, loglik_old, new_to_old, old_to_new)
}

